api:
  restart: always
  build: ./proqodpy
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env
  command: /usr/local/bin/gunicorn proqodpy.wsgi:application -w 2 -b :8000 --reload

front:
  restart: always
  build: ./frontend
  links:
    - api:api
  expose:
    - "9000"
  command: NODE_ENV=production harp server -p 9000 .

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - front
    - api
  links:
    - front:front
    - api:api

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

# r-base:
#   restart: always
#   image: r-base:latest

